# Waits for a statefulset/deploymentConfig/deployment to reach a desired set of replicas

# Vars:
# TARGET_NAMESPACE: string
# COMPONENT_TYPE: string
# COMPONENT_NAME: string
# DELAY: number

# ====== scaling up ===============
- name: Wait for {{ COMPONENT_TYPE}} {{ COMPONENT_NAME }} pods to be scaled up into a ready state in {{ TARGET_NAMESPACE }} 
  shell: oc -n {{ TARGET_NAMESPACE }} get {{ COMPONENT_TYPE }}/{{ COMPONENT_NAME }} -o json
  register: result
  until: ((result.stdout|from_json).status.readyReplicas is defined) and ((result.stdout|from_json).status.readyReplicas|int == (result.stdout|from_json).spec.replicas|int) 
  delay: "{{ DELAY | default(15) }}"
  retries: 45
